name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: build and push image
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: schweizerischebundesbahnen/zally-server
        path: ./server
        tag_with_ref: true
        add_git_labels: true
        build_args: MAKE_TARGET=build
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
