# ./.github/workflows/main.yml

name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Server Image to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: schweizerischebundesbahnen/zally-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true
        dockerfile: ./server/Dockerfile
    - name: Publish Web-UI Image to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: schweizerischebundesbahnen/zally-web-ui
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true
        dockerfile: ./web-ui/Dockerfile
