name: Build & Deploy latest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Docker Repository
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Build: Docker image"
      run: |
        docker build \
        -t docker.pkg.github.com/schweizerischebundesbahnen/zally/zally-server:latest \
        .
    - name: "Push docker image as latest"
      run: docker push docker.pkg.github.com/schweizerischebundesbahnen/zally/zally-server:latest
