name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout
      uses: actions/checkout@v2
      
#    - name: Login to GitHub Docker Repository
#      uses: azure/docker-login@v1
#      with:
#        login-server: docker.pkg.github.com
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: sigibe/zally/zally-server
        path: ./server
        tags: latest
