name: Build & Deploy latest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Repository
      uses: azure/docker-login@v1
      with:
        login-server: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Build: Docker image"
      run: |
        docker build \
        -t schweizerischebundesbahnen/zally-server:latest \
        ./server
    - name: "Push docker image as latest"
      run: docker push schweizerischebundesbahnen/zally-server:latest
